'use client';

import { useMemo, useState } from 'react';

type View = 'monitor' | 'pool' | 'analysis' | 'tasks';
const events = [
  { id:'EV-0909-018', title:'某车型智能驾驶功能体验引发讨论', source:'微博', dept:'乘用车事业群', heat:'8,426', nature:'重点关注', level:'red', time:'10分钟前', checked:true },
  { id:'EV-0909-017', title:'用户反馈售后网点维修等待时间较长', source:'抖音', dept:'售后服务事业部', heat:'2,180', nature:'负面', level:'orange', time:'24分钟前', checked:true },
  { id:'EV-0909-016', title:'新车型交付体验分享持续升温', source:'小红书', dept:'王朝网销售事业部', heat:'936', nature:'中性', level:'blue', time:'42分钟前', checked:true },
  { id:'EV-0909-015', title:'充电服务政策相关信息解读', source:'新闻', dept:'待确认', heat:'415', nature:'待研判', level:'blue', time:'1小时前', checked:false },
];
const divisionEvents = [
  { id:'BU-0910-006', title:'用户反馈城区辅助驾驶偶发退出', source:'抖音', dept:'乘用车事业群', heat:'1,268', nature:'负面', level:'orange', time:'8分钟前', checked:true },
  { id:'BU-0910-005', title:'新车型交付周期相关讨论', source:'微博', dept:'乘用车事业群', heat:'786', nature:'中性', level:'blue', time:'35分钟前', checked:true },
  { id:'BU-0910-004', title:'车机系统升级体验反馈', source:'小红书', dept:'乘用车事业群', heat:'524', nature:'待研判', level:'blue', time:'1小时前', checked:false },
  { id:'BU-0909-021', title:'门店试驾服务流程建议', source:'快手', dept:'乘用车事业群', heat:'312', nature:'中性', level:'blue', time:'昨天', checked:true },
];
const nav:{key:View;label:string;icon:string;count?:number}[]=[
  {key:'monitor',label:'主动监测',icon:'⌁'},{key:'pool',label:'统一事件池',icon:'▦',count:24},{key:'analysis',label:'Agent 研判',icon:'✦',count:3},{key:'tasks',label:'协商任务',icon:'◌',count:8}
];

export default function Home(){
  const [view,setView]=useState<View>('monitor'); const [role,setRole]=useState<'舆情部'|'事业部'>('舆情部');
  const [tab,setTab]=useState<'stream'|'import'>('stream'); const [query,setQuery]=useState(''); const [toast,setToast]=useState(''); const [chat,setChat]=useState('');
  const [messages,setMessages]=useState([{who:'李然 · 舆情部',text:'系统识别该事件涉及智能驾驶功能，请协助确认业务归属和处理建议。',mine:false,time:'10:32'},{who:'周宁 · 乘用车事业群',text:'已确认归属我部门，建议先补充技术说明，再同步准备评论引导口径。',mine:true,time:'10:38'}]);
  const roleEvents=role==='事业部'?divisionEvents:events;
  const visible=useMemo(()=>roleEvents.filter(e=>e.title.includes(query)||e.dept.includes(query)||e.source.includes(query)),[query,role]);
  function flash(s:string){setToast(s);window.setTimeout(()=>setToast(''),2200)}
  function send(){if(!chat.trim())return;setMessages([...messages,{who:role==='舆情部'?'李然 · 舆情部':'周宁 · 乘用车事业群',text:chat,mine:true,time:'现在'}]);setChat('')}
  return <main className="shell"><aside className="side">
    <div className="brand"><i>舆</i><div><strong>舆情协同 Agent</strong><span>INTELLIGENCE HUB</span></div></div>
    <div className="roles"><button className={role==='舆情部'?'on':''} onClick={()=>{setRole('舆情部');setView('monitor');setQuery('')}}>舆情部</button><button className={role==='事业部'?'on':''} onClick={()=>{setRole('事业部');setView('monitor');setQuery('')}}>事业部</button></div>
    <p className="navtitle">核心工作台</p><nav>{nav.map(n=><button key={n.key} className={view===n.key?'selected':''} onClick={()=>setView(n.key)}><i>{n.icon}</i><span>{role==='事业部'&&n.key==='monitor'?'提交舆情链接':n.label}</span>{n.count&&<b>{role==='事业部'&&n.key==='pool'?divisionEvents.length:n.count}</b>}</button>)}</nav>
    <p className="navtitle">管理与配置</p><nav><button onClick={()=>flash('媒体库已配置 1,286 个账号')}><i>◎</i><span>媒体与人员库</span></button><button onClick={()=>flash('规则中心暂用预设规则')}><i>⌘</i><span>规则中心</span></button></nav>
    <div className="service"><i/><div><strong>监测服务运行中</strong><small>最近同步 09:41:26</small></div></div><div className="profile"><i>李</i><div><strong>李然</strong><small>{role} · 管理员</small></div><b>···</b></div>
  </aside><section className="work"><header><div><p>{role}工作台 / {role==='事业部'&&view==='monitor'?'提交舆情链接':nav.find(n=>n.key===view)?.label}</p><h1>{view==='monitor'?(role==='舆情部'?'主动监测与信息接入':'提交舆情链接'):view==='pool'?(role==='舆情部'?'统一舆情事件池':'本事业部舆情记录'):view==='analysis'?'Agent 智能研判':'协商任务中心'}</h1></div><div className="headActions"><button>⌕</button><button>◔</button>{role==='舆情部'&&<button className="primary" onClick={()=>{setView('monitor');setTab('import')}}>＋ 导入供应商总表</button>}</div></header>
    {view==='monitor'&&<Monitor role={role} tab={tab} setTab={setTab} setView={setView} flash={flash}/>} {view==='pool'&&(role==='事业部'?<DivisionPool data={visible} query={query} setQuery={setQuery} setView={setView}/>:<Pool data={visible} query={query} setQuery={setQuery} setView={setView}/>)} {view==='analysis'&&<Analysis setView={setView} flash={flash}/>} {view==='tasks'&&(role==='事业部'?<DivisionTaskCenter messages={messages} chat={chat} setChat={setChat} send={send} flash={flash}/>:<Tasks role={role} messages={messages} chat={chat} setChat={setChat} send={send} flash={flash}/>)} </section>{toast&&<div className="toast">✓ {toast}</div>}</main>
}

function Monitor({role,...props}:{role:'舆情部'|'事业部';tab:'stream'|'import';setTab:(v:'stream'|'import')=>void;setView:(v:View)=>void;flash:(s:string)=>void}){return role==='事业部'?<DivisionSubmit setView={props.setView} flash={props.flash}/>:<OpinionMonitor {...props}/>}

function DivisionSubmit({setView,flash}:{setView:(v:View)=>void;flash:(s:string)=>void}){
  const [url,setUrl]=useState(''); const [summary,setSummary]=useState(''); const [solution,setSolution]=useState('');
  return <div className="page divisionPage"><div className="divisionGrid"><section className="panel submitCard"><div className="panelHead"><div><h2>发起舆情处理申请</h2><p>填写链接及简要信息，直接发送给舆情部对接人</p></div><b>乘用车事业群</b></div><div className="directForm"><Field label="舆情链接"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="粘贴微博、抖音、快手、新闻等舆情链接"/></Field><Field label="简述舆情内容"><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="说明舆情反映的主要问题、涉及车型或业务场景"/></Field><Field label="简述解决方案"><textarea value={solution} onChange={e=>setSolution(e.target.value)} placeholder="填写事业部建议的处理方式，也可以填写“待协商”"/></Field><div className="receiver"><div><span>发送至</span><Person char="李" name="李然" note="舆情部 · 默认对接人"/></div><button onClick={()=>flash('已打开舆情部人员列表')}>更换对接人</button></div><button className="primary full" onClick={()=>{flash('舆情处理申请已发送');setView('tasks')}}>发起协商邀请 →</button></div></section><aside><section className="panel myOverview"><h3>本事业部申请</h3><div><strong>4</strong><span>当前事件</span></div><div><strong>2</strong><span>协商中</span></div><div><strong>1</strong><span>待确认方案</span></div><button onClick={()=>setView('pool')}>查看统一事件池 →</button></section><section className="panel contact"><h3>填写说明</h3><p>提交后将生成一条标准舆情记录，并同步进入本事业部事件池与双方协商任务。</p><p>事业部无需整理供应商表格，也无需等待Agent抓取网页后才能发起沟通。</p></section></aside></div></div>
}

function OpinionMonitor({tab,setTab,setView,flash}:{tab:'stream'|'import';setTab:(v:'stream'|'import')=>void;setView:(v:View)=>void;flash:(s:string)=>void}){return <div className="page"><div className="stats"><Stat n="1,284" label="今日监测链接" note="↑ 12.4%"/><Stat n="86" label="新增舆情事件" note="↑ 8.2%"/><Stat n="12" label="重点关注事件" note="较昨日 +2" tone="red"/><Stat n="3" label="待人工复核" note="需要确认" tone="orange"/></div><div className="roleBanner opinion"><div><small>舆情部专属工作台</small><h2>监测全局、统一研判并批量分发</h2><p>接收供应商总表和事业部申请，匹配60+位事业部对接人。</p></div><button onClick={()=>setTab('import')}>导入供应商总表 →</button></div><div className="monitorGrid"><section className="panel"><div className="panelHead"><div><h2>实时信息流</h2><p>聚合供应商监测与事业部主动上报</p></div><div className="tabs"><button className={tab==='stream'?'on':''} onClick={()=>setTab('stream')}>实时流</button><button className={tab==='import'?'on':''} onClick={()=>setTab('import')}>批量导入</button></div></div>{tab==='stream'?<div className="feed">{events.map((e,i)=><article key={e.id} onClick={()=>setView('analysis')}><div className={`source s${i}`}>{e.source[0]}</div><div><p className="meta">{e.source}　·　{e.time} {i===0&&<em>传播加速</em>}</p><h3>{e.title}</h3><p className="desc">{i===0?'相关讨论集中在功能体验、场景适用范围和官方说明，Agent 已聚合 32 条相似内容。':'Agent 已完成基础信息抽取，等待进入统一事件池完成归属与性质研判。'}</p><div className="tags"><span># {e.dept}</span><span>传播量 {e.heat}</span><span>相似内容 {32-i*7} 条</span></div></div><b className={`risk ${e.level}`}>{e.level==='red'?'红色':e.level==='orange'?'橙色':'蓝色'}</b></article>)}</div>:<div className="upload" onClick={()=>flash('模拟导入成功：识别 128 条记录')}><i>⇧</i><h3>上传供应商舆情总表</h3><p>支持 Excel / CSV，自动校验、去重并转换为标准舆情记录</p><button>选择文件</button><small>Demo 使用模拟数据，不会上传真实文件</small></div>}</section><aside><section className="panel agent"><div className="agentHead"><i>✦</i><div><h2>Agent 运行状态</h2><p>正在持续分析新信息</p></div><b>运行中</b></div><div className="pipeline"><Pipe n="01" title="内容采集" note="1,284 条已接入" done/><Pipe n="02" title="去重与事件聚合" note="86 个事件" done/><Pipe n="03" title="标签与等级研判" note="3 条待复核" active/><Pipe n="04" title="责任部门匹配" note="自动匹配率 92%"/></div></section><section className="panel quick"><i>↗</i><div><h3>待分发申请</h3><p>7条事业部上报等待舆情人员接收</p></div><button onClick={()=>setView('tasks')}>去处理</button></section></aside></div></div>}

function DivisionDashboard({setView,flash}:{setView:(v:View)=>void;flash:(s:string)=>void}){const[url,setUrl]=useState('');const[parsed,setParsed]=useState(false);return <div className="page divisionPage"><div className="roleBanner division"><div><small>事业部专属工作台</small><h2>发现舆情，一键发起处理申请</h2><p>无需整理供应商表格，粘贴链接后由Agent生成统一舆情表。</p></div><span>乘用车事业群 · 周宁</span></div><div className="divisionGrid"><section className="panel submitCard"><div className="panelHead"><div><h2>提交舆情链接</h2><p>Agent将自动读取文章并补齐标准申请字段</p></div><b>STEP 1 / 2</b></div><div className="urlInput"><label>舆情链接</label><textarea value={url} onChange={e=>setUrl(e.target.value)} placeholder="粘贴微博、抖音、快手、新闻等舆情链接，可一次输入多条"/><small>系统仅解析你主动提交的链接，不会代表事业部主动全网监测。</small><button className="primary" onClick={()=>{setParsed(true);flash('Agent 已生成舆情处理申请')}}>✦ Agent 解析并生成申请</button></div>{parsed&&<div className="generated"><div className="generatedHead"><div><i>✓</i><span><strong>申请表已生成</strong><small>请确认信息后发给舆情部对接人</small></span></div><b>Agent 置信度 92%</b></div><div className="formGrid"><Field label="事件"><input defaultValue="智能驾驶功能体验讨论"/></Field><Field label="事业部"><input defaultValue="乘用车事业群"/></Field><Field label="传播率"><input defaultValue="持续上升"/></Field><Field label="性质"><select defaultValue="待舆情部研判"><option>待舆情部研判</option><option>负面</option><option>中性</option></select></Field><Field label="处理意见"><input defaultValue="待双方协商"/></Field><Field label="处理媒介（处理部门）"><select defaultValue="李然 · 舆情部"><option>李然 · 舆情部</option><option>陈洁 · 舆情部</option><option>王铭 · 舆情部</option></select></Field></div><button className="primary full" onClick={()=>setView('tasks')}>向李然发起协商邀请 →</button></div>}</section><aside><section className="panel myOverview"><h3>我的申请</h3><div><strong>6</strong><span>本月提交</span></div><div><strong>2</strong><span>协商中</span></div><div><strong>3</strong><span>已形成方案</span></div><button onClick={()=>setView('tasks')}>查看全部任务 →</button></section><section className="panel contact"><h3>默认舆情对接人</h3><Person char="李" name="李然" note="舆情部 · 当前在线"/><p>系统根据事业部人员映射自动推荐，也可以在提交时更换。</p><button onClick={()=>flash('已打开舆情部人员列表')}>更换对接人</button></section></aside></div></div>}
function Stat({n,label,note,tone}:{n:string;label:string;note:string;tone?:string}){return <div className={`stat ${tone||''}`}><p>{label}</p><strong>{n}</strong><span>{note}</span><i/></div>}
function Pipe({n,title,note,done,active}:{n:string;title:string;note:string;done?:boolean;active?:boolean}){return <div className={`pipe ${active?'active':''}`}><i>{done?'✓':n}</i><div><strong>{title}</strong><small>{note}</small></div>{active&&<em>处理中</em>}</div>}

function DivisionPool({data,query,setQuery,setView}:{data:typeof events;query:string;setQuery:(s:string)=>void;setView:(v:View)=>void}){return <div className="page"><div className="toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索本事业部事件或平台"/></label><button className="on">全部 {data.length}</button><button>协商中 2</button><button>待确认 1</button><button>已完成 1</button></div><section className="panel table"><table><thead><tr><th>事件</th><th>来源</th><th>传播量</th><th>性质</th><th>事业部</th><th>协商状态</th><th/></tr></thead><tbody>{data.map((e,i)=><tr key={e.id} onClick={()=>setView('tasks')}><td><small>{e.id}</small><strong>{e.title}</strong></td><td><span>{e.source}</span></td><td>{e.heat}</td><td><span className={`nature ${e.level}`}>{e.nature}</span></td><td><b>{e.dept}</b></td><td>{i<2?<b className="pending">协商中</b>:<b className="done">{i===2?'待确认':'已完成'}</b>}</td><td>›</td></tr>)}</tbody></table></section></div>}

function Pool({data,query,setQuery,setView}:{data:typeof events;query:string;setQuery:(s:string)=>void;setView:(v:View)=>void}){return <div className="page"><div className="toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索事件、事业部或平台"/></label><button className="on">全部 24</button><button>待研判 3</button><button>协商中 8</button><button>已完成 13</button></div><section className="panel table"><table><thead><tr><th>事件</th><th>来源</th><th>传播量</th><th>性质</th><th>事业部</th><th>Agent 状态</th><th/></tr></thead><tbody>{data.map(e=><tr key={e.id} onClick={()=>setView(e.checked?'tasks':'analysis')}><td><small>{e.id}</small><strong>{e.title}</strong></td><td><span>{e.source}</span></td><td>{e.heat}</td><td><span className={`nature ${e.level}`}>{e.nature}</span></td><td>{e.dept}</td><td>{e.checked?<b className="done">✓ 已研判</b>:<b className="pending">✦ 待复核</b>}</td><td>›</td></tr>)}</tbody></table></section></div>}

function Analysis({setView,flash}:{setView:(v:View)=>void;flash:(s:string)=>void}){const[dept,setDept]=useState('待确认');return <div className="page analysis"><section className="panel preview"><div className="previewTop"><div className="source">微</div><div><p>微博 · 10分钟前</p><h2>某车型智能驾驶功能体验引发讨论</h2></div></div><p>近日，有用户发布相关车型智能驾驶功能体验内容，讨论集中于复杂道路场景下的功能表现和适用范围……</p><div className="media"><span>文章内容预览</span><strong>8,426</strong><small>当前传播量</small></div><a>查看原始链接 ↗</a></section><section className="panel judgement"><div className="agentHead"><i>✦</i><div><h2>Agent 研判结果</h2><p>基于内容、传播与媒体关系分析</p></div><b>置信度 91%</b></div><Field label="事件"><input defaultValue="智能驾驶功能体验讨论"/></Field><div className="two"><Field label="性质"><select defaultValue="重点关注"><option>重点关注</option><option>负面</option><option>中性</option></select></Field><Field label="事件等级"><select defaultValue="红色"><option>红色</option><option>橙色</option><option>蓝色</option></select></Field></div><Field label="责任事业部"><select value={dept} onChange={e=>setDept(e.target.value)}><option>待确认</option><option>乘用车事业群</option><option>售后服务事业部</option><option>品牌及公关处</option></select><small>匹配依据：内容涉及智能驾驶功能与车辆使用场景</small></Field><div className="tagBox"><label>智能标签</label><div><span>比亚迪相关 ×</span><span>车主发布 ×</span><span>无官方回应 ×</span><span>非 MCN ×</span><button>＋ 添加</button></div></div><div className="reason"><strong>判定依据</strong><p>传播量超过重点阈值，且出现主流媒体跟进讨论，建议升级为红色事件并立即发起协商。</p></div><div className="actions"><button onClick={()=>flash('已保存为待复核记录')}>保存待复核</button><button className="primary" onClick={()=>setView('tasks')}>确认并发起协商 →</button></div></section></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}

function DivisionTaskCenter({messages,chat,setChat,send,flash}:{messages:{who:string;text:string;mine:boolean;time:string}[];chat:string;setChat:(s:string)=>void;send:()=>void;flash:(s:string)=>void}){
  const [active,setActive]=useState<'started'|'pending'>('started'); const [selected,setSelected]=useState(0);
  const started=divisionEvents.slice(0,2); const pending=divisionEvents.slice(2); const list=active==='started'?started:pending; const current=list[selected]||list[0];
  const statuses=active==='started'?['协商中','待舆情部接收']:['待我确认','处理中'];
  return <div className="page taskGrid"><section className="panel taskList"><div className="taskTabs"><button className={active==='started'?'on':''} onClick={()=>{setActive('started');setSelected(0)}}>我发起的 <b>{started.length}</b></button><button className={active==='pending'?'on':''} onClick={()=>{setActive('pending');setSelected(0)}}>待我处理 <b>{pending.length}</b></button></div>{list.map((e,i)=><article className={selected===i?'on':''} key={e.id} onClick={()=>setSelected(i)}><p className="taskMeta"><i className={`d${i}`}/> {statuses[i]}<time>{e.time}</time></p><h3>{e.title}</h3><p>{active==='started'?'乘用车事业群 → 李然 · 舆情部':'李然 · 舆情部 → 乘用车事业群'}</p><div className="tags"><span>{e.source}</span><span>{e.dept}</span></div></article>)}</section><section className="panel conversation"><div className="conversationHead"><div><h2>{current.title}</h2><p>任务 {current.id} · <span>{statuses[selected]}</span></p></div><button onClick={()=>flash('任务详情已展开')}>···</button></div><div className="taskOrigin"><span>{active==='started'?'事业部主动发现并发起':'舆情部监测后分发'}</span><p>{active==='started'?'等待舆情部共同确认处理方式':'请事业部确认归属并反馈建议解决方案'}</p></div><div className="context"><div><span>事件性质<strong>{current.nature}</strong></span><span>传播量<strong>{current.heat}</strong></span><span>事业部<strong>{current.dept}</strong></span></div><a>查看事件详情 ›</a></div><div className="messages"><p className="day">今天</p>{messages.map((m,i)=><div className={`message ${m.mine?'mine':''}`} key={i}><i>{m.who[0]}</i><div><p>{m.who}　{m.time}</p><span>{m.text}</span></div></div>)}</div><div className="quickActions"><button onClick={()=>setChat(active==='started'?'补充说明：事业部建议尽快统一答复口径。':'已确认该事件归属乘用车事业群，建议补充官方说明。')}>＋ {active==='started'?'补充解决方案':'确认并反馈方案'}</button><button onClick={()=>flash('已打开舆情部人员列表')}>⇄ 更换对接人</button></div><div className="composer"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="向舆情部对接人发送协商内容…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div><span>⌕　▣　＠</span><button onClick={send}>发送 ↗</button></div></div></section><aside className="taskSide"><section className="panel plan"><h3>{active==='started'?'事业部建议方案':'待处理要求'}</h3><div><i>⌁</i><p>{active==='started'?'等待双方协商确认最终处理方式':'请确认事业部归属并提出解决方案'}</p><button onClick={()=>flash('解决方案已补充')}>补充方案</button></div></section><section className="panel people"><h3>协商双方</h3><Person char={active==='started'?'周':'李'} name={active==='started'?'周宁':'李然'} note={active==='started'?'乘用车事业群 · 发起人':'舆情部 · 发起人'}/><Person char={active==='started'?'李':'周'} name={active==='started'?'李然':'周宁'} note={active==='started'?'舆情部 · 接收人':'乘用车事业群 · 接收人'}/></section></aside></div>
}

function DivisionTasks({messages,chat,setChat,send,flash}:{messages:{who:string;text:string;mine:boolean;time:string}[];chat:string;setChat:(s:string)=>void;send:()=>void;flash:(s:string)=>void}){const current=divisionEvents[0];return <div className="page taskGrid"><section className="panel taskList"><div className="taskTabs"><button className="on">我发起的 <b>{divisionEvents.length}</b></button><button>待我确认</button></div>{divisionEvents.slice(0,3).map((e,i)=><article className={i===0?'on':''} key={e.id}><p className="taskMeta"><i className={`d${i}`}/> {i===0?'协商中':i===1?'待舆情部接收':'待确认方案'}<time>{e.time}</time></p><h3>{e.title}</h3><p>乘用车事业群 → 李然 · 舆情部</p><div className="tags"><span>{e.source}</span><span>{e.dept}</span></div></article>)}</section><section className="panel conversation"><div className="conversationHead"><div><h2>{current.title}</h2><p>任务 {current.id} · <span>协商中</span></p></div><button onClick={()=>flash('任务详情已展开')}>···</button></div><div className="context"><div><span>事件性质<strong>{current.nature}</strong></span><span>传播量<strong>{current.heat}</strong></span><span>事业部<strong>{current.dept}</strong></span></div><a>查看事件详情 ›</a></div><div className="messages"><p className="day">今天</p>{messages.map((m,i)=><div className={`message ${m.mine?'mine':''}`} key={i}><i>{m.who[0]}</i><div><p>{m.who}　{m.time}</p><span>{m.text}</span></div></div>)}</div><div className="quickActions"><button onClick={()=>setChat('事业部建议解决方案：补充官方说明，并同步一线门店统一答复口径。')}>＋ 补充解决方案</button><button onClick={()=>flash('已打开舆情部人员列表')}>⇄ 更换对接人</button></div><div className="composer"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="向舆情部对接人发送协商内容…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div><span>⌕　▣　＠</span><button onClick={send}>发送 ↗</button></div></div></section><aside className="taskSide"><section className="panel plan"><h3>事业部建议方案</h3><div><i>⌁</i><p>等待双方协商确认最终处理方式</p><button onClick={()=>flash('解决方案已补充')}>补充方案</button></div></section><section className="panel people"><h3>协商双方</h3><Person char="周" name="周宁" note="乘用车事业群 · 发起人"/><Person char="李" name="李然" note="舆情部 · 接收人"/></section></aside></div>}

function Tasks({role,messages,chat,setChat,send,flash}:{role:string;messages:{who:string;text:string;mine:boolean;time:string}[];chat:string;setChat:(s:string)=>void;send:()=>void;flash:(s:string)=>void}){return <div className="page taskGrid"><section className="panel taskList"><div className="taskTabs"><button className="on">待我处理 <b>4</b></button><button>我发起的</button></div>{events.slice(0,3).map((e,i)=><article className={i===0?'on':''} key={e.id}><p className="taskMeta"><i className={`d${i}`}/> {i===0?'协商中':i===1?'待接收':'待确认方案'}<time>{e.time}</time></p><h3>{e.title}</h3><p>{i===0?'李然 · 舆情部 → 周宁 · 乘用车事业群':'系统已匹配双方默认对接人'}</p><div className="tags"><span>{e.source}</span><span>{e.dept}</span></div></article>)}</section><section className="panel conversation"><div className="conversationHead"><div><h2>某车型智能驾驶功能体验引发讨论</h2><p>任务 EV-0909-018 · <span>协商中</span></p></div><button onClick={()=>flash('任务详情已展开')}>···</button></div><div className="context"><div><span>事件性质<strong>重点关注</strong></span><span>传播量<strong>8,426</strong></span><span>责任事业部<strong>乘用车事业群</strong></span></div><a>查看事件详情 ›</a></div><div className="messages"><p className="day">今天</p>{messages.map((m,i)=><div className={`message ${m.mine?'mine':''}`} key={i}><i>{m.who[0]}</i><div><p>{m.who}　{m.time}</p><span>{m.text}</span></div></div>)}</div><div className="quickActions"><button onClick={()=>setChat('建议处理方式：投诉 + 评论引导；请于今日 18:00 前反馈处理结果。')}>＋ 提议处理方案</button><button onClick={()=>flash('已打开转交人员列表')}>⇄ 转交</button><button onClick={()=>flash('已标记为紧急任务')}>! 标记紧急</button></div><div className="composer"><textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder={`以${role}身份输入协商内容…`} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div><span>⌕　▣　＠</span><button onClick={send}>发送 ↗</button></div></div></section><aside className="taskSide"><section className="panel plan"><h3>处理方案</h3><div><i>⌁</i><p>双方确认后形成结构化方案</p><button onClick={()=>flash('已生成处理方案草稿')}>生成方案草稿</button></div></section><section className="panel people"><h3>协作成员</h3><Person char="李" name="李然" note="舆情部 · 发起人"/><Person char="周" name="周宁" note="乘用车事业群 · 接收人"/><button onClick={()=>flash('可从已配置的 60+ 位对接人中邀请')}>＋ 邀请协作人</button></section></aside></div>}
function Person({char,name,note}:{char:string;name:string;note:string}){return <p><i>{char}</i><b>{name}<small>{note}</small></b></p>}
